= login-filter: Filter-based Login mechanism

This is a skeleton of a Java EE Filter-based Login mechanism that I intially
wrote in 2006 to compare with a Struts-based login.

To keep the code focused on its topic, there is no database checking so the login name and
password are hardcoded; in short, it is just the bare essentials 
needed to demonstrate this type of login mechanism.

You can use this for anything with credit and without fee.

For a more comprehensive implementation of this idea (unrelated to my
implementation), look  for a project called "securityfilter" (which is currently at
http://securityfilter.sourceforge.net/).

-- Production?

If you are going to use this in production, you can either change the login() method
here to use JPA or JDBC to lookup the encrytped password in your database, or, set up
a Java EE Real with users, then use the
Servlet 3.0 request.login() to verify the user/password AND to obviate the need for the LoginFilterHTTPServletRequest.java

Ian Darwin
http://www.darwinsys.com/
